package metaphorDemo;

/*The class defined the path and filenames of the data sources
 */
public class DataSource {
		/* path to the data source, different from system */
		public static final String RESOURCE_PATH = "/Users/AceYan/apps/apache-tomcat/resources/";
		/* filename of cleaned metaphor-source-target labeled file with domain tags */
		public static final String MST = "comprehensive_domain_tags.json";
		/* filename of the term vector index file which is generated by SemanticVector3.8 */
		public static final String TERM_Vector = "termvectors.bin";
		/* filename of the document vector index file which is generated by SemanticVector3.8 */
		public static final String DOC_Vector = "docvectors.bin";
		/* filename of the domain statistics file */
		public static final String DOMAIN_STAT = "domain_tag_statistics.txt";
}
